version: '3.3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - '8009:8000'
    networks:
      - backend-net

networks:
  backend-net:
    external: true
